name: Crystal CI

on:
  push:
  pull_request:
  schedule:
    # At 00:00 on Sunday
    - cron: '0 0 * * 0'

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Check format
        run: crystal tool format --check

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Run tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: crystal spec
